---
title: "RF_diabetes"
author: "Yichen Zhao"
date: "2024-12-13"
output: html_document
---

```{r, message=FALSE}
# Load the library
library(caret)
library(pROC)
library(ranger)
library(parallel)
```

```{r}
# Load the training (80%) and testing (20%) sets
testData2 <- read.csv("~/Desktop/625_Final/data/test_data.csv")
trainData2 <- read.csv("~/Desktop/625_Final/data/train_data.csv")
```

```{r}
# Turn outcome variable into factor
trainData2$Diabetes_binary <- as.factor(trainData2$Diabetes_binary)
testData2$Diabetes_binary <- as.factor(testData2$Diabetes_binary)
levels(trainData2$Diabetes_binary) <- c("NoDiabetes", "Diabetes")
levels(testData2$Diabetes_binary) <- c("NoDiabetes", "Diabetes")

# Train the Random Forest model
rf_model2 <- train(
    Diabetes_binary ~ ., 
    data = trainData2, 
    method = "rf", 
    trControl = trainControl(method = "cv", number = 8, classProbs = TRUE), 
    tuneGrid = expand.grid(mtry = 3), 
    ntree = 500
  )

# Train the Random Forest model with parallel processing
set.seed(123)
rf_model_ranger <- ranger(
  Diabetes_binary ~ ., 
  data = trainData2,
  num.trees = 500,         
  mtry = 3,                 
  probability = TRUE,       
  num.threads = detectCores() - 1  
)

# Measure time for train
time_train <- system.time({
  rf_model2 <- train(
    Diabetes_binary ~ ., 
    data = trainData2, 
    method = "rf", 
    trControl = trainControl(method = "cv", number = 8, classProbs = TRUE), 
    tuneGrid = expand.grid(mtry = 3), 
    ntree = 500
  )
})

# Measure time for ranger
time_ranger <- system.time({
  rf_model_ranger <- ranger(
    Diabetes_binary ~ ., 
    data = trainData2,
    num.trees = 500,         
    mtry = 3,                 
    probability = TRUE,       
    num.threads = detectCores() - 1  
  )
})

# Compare the timing results
print("Time for the original random forest model")
print(time_train)
print("Time for model using ranger")
print(time_ranger)

# Predict probabilities for the test data
test_probs2 <- predict(rf_model_ranger, data = testData2)$predictions[, "Diabetes"]
test_preds2 <- ifelse(test_probs2 > 0.5, "Diabetes", "NoDiabetes")
```

```{r}
# Compute ROC Curve and AUC
roc_curve2 <- roc(testData2$Diabetes_binary, test_probs2)
auc_value2 <- auc(roc_curve2)
print(paste("AUC for Random Forest Model: ", round(auc_value2, 4)))

# Compute Accuracy
accuracy2 <- mean(test_preds2 == testData2$Diabetes_binary)
print(paste("Accuracy for Ranger Random Forest Model: ", round(accuracy2, 4)))

# Plot the ROC Curve
png("RF_Diabetes.png")
plot(roc_curve2, main = "ROC Curve for Random Forest Model", col = 'blue', lwd = 2)
dev.off()
```

